<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class SearchCompanyRequest extends FormRequest
{

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'inn' => 'min:10,max:10,string'
        ];
    }

    function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
